# Para crear el environment e instalar los paquetes necesarios, una vez descargados los archivos, moverse al directorio y ejectuar:
#         conda env create
#         conda activate PythonAnywhereSite01

# para actualizar (agregar/sacar/modificar versiones), modificar este archivo y despues ejecutar:
#         conda env update --prune

# para limpiar de paquetes instalados manualmente (pruebas), borrar el environment y volverlo a crear:
#         conda deactivate
#         conda env remove -n PythonAnywhereSite01
#         conda env create
#         conda activate PythonAnywhereSite01

name: PythonAnywhereSite01
dependencies:
  - python=3.7
  - numpy
  - pip
  - pip: # PyPI packages
    - django
    - pyenchant
